(defun cuadrado (x) (* x x))
(defun sumadoble (a b) (+ (* a 2) (* b 2)))
(defun factorial (n) (cond ((<= n 1) 1) (t (* n (factorial (- n 1))))))
(defun fibonacci (n) (cond ((<= n 1) n) (t (+ (fibonacci (- n 1)) (fibonacci (- n 2))))))
(cuadrado 5)
(sumasaldoble 3 4)
(factorial 5)
(fibonacci 6)
(setq x 10)
(setq y 20)
(equal x x)
(equal x y)
(list x y (+ x y))
(atom x)
(atom '(1 2 3))
(quote (+ 2 3))
'(a b c)
(setq edad 17)
(cond ((< edad 18) "menor de edad") ((>= edad 18) "mayor de edad"))